### PR TITLE
Laravel 8 Updates Shift

### PR DESCRIPTION
**Pull request by mattstauffer**
This pull request includes changes from recent updates to Laravel core files. Although some of these changes may be considered optional, they are required when you use recently added features - such as the [new validation rules](https://laravel-news.com/laravel-prohibited-validation-rules), [configuration options](https://github.com/laravel-shift/laravel-8.x/compare/6f5bb4700e273ff55468ddcd127027ea4d706d6e..master#diff-950397cc5ef29707b54d0c774bd94af85836bab1a27f2f86533d832d25caf224), or [Laravel Sanctum](https://laravel.com/docs/8.x/sanctum).

Since Laravel has moved to annual release cycles, these changes sometimes reach a critical mass. When they do, you will receive an automated pull request as part of your _Shifty Plan_.

**Before merging**, you need to:

- Checkout the `shift-ci-85` branch
- Review **all** pull request comments for additional changes
- Run `composer update` (if the scripts fail, add `--no-scripts`)
- Clear any config, route, or view cache
- Thoroughly test your application ([no tests?](https://laravelshift.com/laravel-test-generator))

If you would like more detail you may [view the full changes](https://github.com/laravel/laravel/compare/v8.0.0...v8.5.15). Be sure you're opted in to the [Shift Newsletter](https://laravelshift.com/account/preferences) to receive weekly updates for Laravel.

### CODE REVIEW

**Comment by mattstauffer** [comment]
:information_source: The `Request::HEADER_X_FORWARDED_ALL` was deprecated in Symfony 5.2. While Shift attempts to update this within the `TrustProxies` middleware, you should search your code for any additional uses and convert them to [the individual constants](https://github.com/laravel/laravel/blob/6bc0b1cfcbc35d89b3e4ec31d83d7b409f9bf595/app/Http/Middleware/TrustProxies.php#L22) instead.

**Comment by mattstauffer** [comment]
:information_source: Laravel updated the new rate limiters to filter by IP address or the authenticated user. While Shift attempts to update this for the default rate limiter, you may wish to [add this logic](https://github.com/laravel/laravel/blob/57ddc0ebbb1cdc778e301016b643769d1f96e2e1/app/Providers/RouteServiceProvider.php#L60) to any additional rate limiters you added.

**Comment by mattstauffer** [comment]
:warning: Laravel added the `current_password` request parameter to the `TrimStrings` middleware and `dontFlash` exception handler property for better integration with the new _JetStream_ and _Fortify_ starter kits.

If your application uses a `current_password` field which you wish to _trim_ or _flash_, you should undo this change.

**Comment by mattstauffer** [comment]
:information_source: Laravel 8 added a new ENV variable of `LOG_LEVEL` for all log channels. While the log level is defaulted in the configuration, you may take this opportunity to set it accordingly in your environments.

**Comment by mattstauffer** [comment]
:information_source: Shift [updated your dependencies](https://github.com/tighten/novapackages/pull/107/commits/f632c02099375020ba69ac2c8c9dab1a88f62caf?w=1) with the latest constraints from Laravel 8. While many of the popular packages are also reviewed, you may have to update additional packages. Watch [dealing with dependencies](https://laravelshift.com/videos/update-incompatible-composer-dependencies) for tips on handling package incompatibilities.

**Comment by mattstauffer** [comment]
:x: Shift removed your dependency for `laravel-mix-tailwind`. This package is no longer needed with Laravel Mix 6.

However, you will need to update your CSS build for Tailwind to use PostCSS directly, instead of the `tailwind()` helper. For example:

```diff
- mix.postCss('resources/css/app.css', 'public/css')
-     .tailwind('./tailwind.config.js');
+ mix.postCss('resources/css/app.css', 'public/css', [
+     require('tailwindcss'),
+ ]);
```

**Comment by mattstauffer** [comment]
:x: Shift detected Vue components within your `resources` folder. Laravel Mix 6 extracted Vue support into its own feature flag.

You should update your `webpack.mix.js` and append the new `mix.vue()` call when building any Vue components. For example:

```js
mix.js('resources/js/app.js', 'public/js').vue();
```

**Comment by mattstauffer** [comment]
:warning: Shift upgraded your NPM dependencies and scripts for Laravel Mix 6. You will need to run `npm install` locally to ensure your dependencies are up-to-date and compatible.

If you encounter any issues, be sure you have the latest LTS or stable version of Node installed. If the problem persists, review the [Update to Mix 6](https://laravel-mix.com/docs/6.0/upgrade) docs for any additional steps.

**Comment by mattstauffer** [comment]
:warning: Shift detected you are using a Laravel package like Horizon or Nova which may need to have its published assets regenerated after upgrading. Be sure to use `artisan` to _republish_ these assets as well as `php artisan view:clear` to avoid any errors.

**Comment by marcusmoore** [comment]
Going to close this and trigger another shift to get us to the latest, 8.47.0.

**Pull request closed without merging**
