### PR TITLE
Allow packages to be deleted

### LINKED ISSUE #81: Not able to delete
Hi @mattstauffer 

I got an email asking to remove a package if it is no longer maintained. There is not an option I can see to delete the package. 

Happy to PR for this if it doesn't exist, but also, I could be dumb/not looking correctly/both and am missing it

### PR DESCRIPTION
**Pull request by marcusmoore**
This PR allows a package to be deleted by app admins, the package's author and collaborators, as well as the submitter of the package if the package author is not a user of the app. Data associated to the package is deleted along with the package.

A package can be deleted from the edit package view via a new button 
Edit Package page

Before proceeding, a javascript confirmation will pop up to ensure the user's intention: 
Confirmation

After deleting the user is redirected to the app package index page with a confirmation message: 
CleanShot 2021-09-27 at 13 23 46
(The blank space is actually the package's name)

---

Closes #81

### CODE REVIEW

**Comment by mziraki** [comment]
@marcusmoore @mattstauffer
hi, sorry to bother you about this, any update?

**Comment by marcusmoore** [comment]
@mziraki I plan on diving back into this. Is there a specific package you want me to remove of yours now?

**Comment by mziraki** [comment]
@marcusmoore nice, no, just checking, tanx for quick reply

**Comment by dillingham** [comment]
@mziraki lol

**Pull request merged**
