### PR TITLE
Basic Setup For User To Delete Their Packages

### PR DESCRIPTION
**Pull request by devingray**
This is a draft PR for allowing users to delete their packages. 

Currently only admins can disable and enable packages. 

I Would like to open the discussion to the best way forward to find out what else would be needed. 
EG: Dropping from Algolia index

### CODE REVIEW

**Comment by marcusmoore** [comment]
Thanks @devingray. I'll give this a spin later today. I _think_ packages will be removed from Algolia when an eloquent model is deleted but I would have to double-check.

**Comment by devingray** [comment]
I also assumed that, however I didn't have a load of time to properly check it out. 

I think most important is to ensure that this post request is handled correctly in the policy and probably to add in a small confirm dialog. 

Let me get on that

**Comment by marcusmoore** [comment]
Sorry for the delay @devingray...it was a busy week and I haven't had the chance to dive into this yet.

I'm mulling over the implications of deleting packages and wondering if we should disable them instead. I'm going to put some more thought into it and get back to you.

If we decide to delete packages then I think, tentatively, this PR will be ready when:
- Policy is in place to ensure that only authors (and admins) can delete their own packages
- The "Delete Package" button/link is only visible for package authors (and admins)
- A warning dialog pops up that tells users deleting their package is permanent and will remove all reviews and ratings

**Comment by devingray** [comment]
No worries! Let me know your thoughts. Busy week for me too so haven't done much regarding this

**Comment by marcusmoore** [comment]
Hey @devingray, sorry for not getting back to you. This totally dropped off my radar.

@mattstauffer I believe that allowing users to disable their packages would be a good solution, at least for the time being.

@devingray do you have any interest in re-opening and modifying this PR? (Totally ok if not 😄)

**Comment by devingray** [comment]
Hello Beautiful people @mattstauffer and @marcusmoore I will do this tonight

**Pull request closed without merging**
